version: 2
updates:
  - schedule:
      interval: "weekly"
      day: "monday"
      time: "08:00"
      timezone: "America/New_York"
    directories:
      - "/"
    package-ecosystem: "github-actions"
    commit-message:
      prefix: "[JN-1457]"
