steps:
  # 1. check out code and check out tag $TAG_NAME
  - name: 'gcr.io/cloud-builders/git'
    id: Clone env repository
    args: [ 'clone', '--depth', '1', '--branch', '$TAG_NAME', 'https://github.com/broadinstitute/juniper.git', '/workspace/juniper' ]
  # 2. wait for images to be pushed to GAR
  - name: 'gcr.io/cloud-builders/docker'
    id: Wait for images to be pushed
    entrypoint: bash
    args:
      - -c
      - |
        function wait_for_image () {
            echo "attempting to pull $1..."
            until docker pull $1
            do
                echo "image $1 not found..."
                sleep 5
                echo "attempting to pull $1..."
            done
            echo "found $1!"
        }
        
        wait_for_image "us-central1-docker.pkg.dev/broad-juniper-eng-infra/juniper/juniper-admin:$TAG_NAME"
        wait_for_image "us-central1-docker.pkg.dev/broad-juniper-eng-infra/juniper/juniper-participant:$TAG_NAME"
  # 3. once images are pushed, helm upgrade the deployment
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    dir: /workspace/juniper/terraform/gcp/k8s
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1'
      - 'CLOUDSDK_CONTAINER_CLUSTER=juniper-cluster'
    entrypoint: bash
    args:
      - -c
      - |
        gcloud container clusters get-credentials juniper-cluster --zone us-central1
        curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash        
        helm upgrade -f environments/$_ENV.yaml juniper . --namespace $_NAMESPACE
options:
  logging: CLOUD_LOGGING_ONLY
  pool:
    name: 'projects/$PROJECT_ID/locations/us-central1/workerPools/juniper-deployment-worker-pool'
