 databaseChangeLog:
   - changeSet:
       id: "maintenance_mode_settings"
       author: mbemis
       changes:
          - createTable:
               tableName: maintenance_mode
               columns:
                - column:
                     { name: message, type: varchar(255), constraints: { nullable: true } }
                - column:
                     { name: password, type: varchar(255), constraints: { nullable: true } }
                - column:
                     { name: enabled, type: boolean, constraints: { nullable: false } }
                - column:
                     { name: disable_scheduled_jobs, type: boolean, constraints: { nullable: false } }
